language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run deploy
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
